import { ICategoryBackend } from './categories/categoriesInterfaces';
import { IProductBackend } from './products/productsInterfaces';

export const productSeed: IProductBackend[] = [
  {
    id: '1Popf5jEwQE0HlcCjQ9P',
    onSale: false,
    isNew: true,
    onCombo: false,
    isFeatured: false,
    name: 'Polvo Decolorante para pelo natural.',
    stock: 10,
    minStock: 2,
    sku: '4567788',
    brand: 'Issue',
    category: 'Decolorantes',
    description:
      'ISSUE ACLARO Y PUNTO POLVO DECOLORANTE X 700GR\nPolvo Decolorante Para Cabellos Naturales.\nPolvo Decolorante Issue Aclaro y Punto es ideal para una máxima aclaración. Ideal para cabellos naturales permite una máxima decoloración sin dañar el cabello.\nEs el polvo decolorante tradicional líder del mercado. Alto rendimiento e ideal para trabajos con gorro y para una máxima decoloración. Decolora en forma pareja y uniforme. Aclara hasta 7 tonos.',
    dimensions: {},
    price: 1100,
    salePrice: 1100,
    discount: 0,
    image:
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Faclaro%20y%20punto.jpeg?alt=media&token=802ca16f-ae34-41d8-8b1d-937c6534288e',
    gallery: [
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Faclaro%20y%20punto.jpeg?alt=media&token=802ca16f-ae34-41d8-8b1d-937c6534288e',
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Faclaro%20y%20punto.jpeg?alt=media&token=802ca16f-ae34-41d8-8b1d-937c6534288e',
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Faclaro%20y%20punto.jpeg?alt=media&token=802ca16f-ae34-41d8-8b1d-937c6534288e',
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Faclaro%20y%20punto.jpeg?alt=media&token=802ca16f-ae34-41d8-8b1d-937c6534288e',
    ],

    variants: false,
  },
  {
    id: '6fGjRYY4dag4vyIykb1M',
    onSale: false,
    isNew: false,
    onCombo: false,
    isFeatured: false,
    name: 'Tintura Splendore',
    stock: 10,
    minStock: 2,
    sku: '',
    brand: 'MAV',
    category: 'Tinturas',
    description: 'Pomo de tintura permanente de 60grs.',
    dimensions: {},
    price: 300,
    salePrice: 300,
    discount: 0,
    image:
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Ftintura.jpeg?alt=media&token=9bde6dc6-46d9-4281-84bc-d02986ecefa7',
    gallery: [
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Ftintura.jpeg?alt=media&token=9bde6dc6-46d9-4281-84bc-d02986ecefa7',
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Ftintura.jpg?alt=media&token=556d994b-6cb8-43e7-986f-be32fe14ae9e',
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Ftintura2.jpg?alt=media&token=a3e33efd-237c-44b1-b43e-d48173a8679b',
    ],
    variants: false,
  },
  {
    id: 'Cg7rcp6r1cryCKPgN7bg',
    onSale: false,
    isNew: true,
    onCombo: true,
    isFeatured: false,
    name: 'Máscara capilar extra ácida',
    stock: 8,
    minStock: 2,
    sku: '',
    brand: 'MAV',
    category: 'Tratamiento capilar',
    description:
      'Mascara Mav extra acida 250g\n\nLa máscara extra ácida fue formulada con materias primas seleccionadas para asegurar el aporte de nutrientes al cabello. Gracias a su pH extra ácido, logra restaurar la fibra capilar en su totalidad, sellando la cutícula y luciendo un cabello brillante y sedoso. Gran poder desenredante ideal para finalizar trabajos técnicos y nivelar el pH final. Otorga hidratación profunda a cabellos dañados y muy castigados.\n- 250gr\n\nModo de uso:\nAplicar la cantidad necesaria sobre el cabello mojado evitando la raíz. Dejar actuar de 5 a 10 minutos. Enjuagar bien.',
    dimensions: {},
    price: 480,
    salePrice: 480,
    discount: 0,
    image:
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Fmascara%20capilar%20de%20tratamiento%20extra%20acida.jpeg?alt=media&token=04e33800-b615-4973-8ca6-fa13eb74621e',
    gallery: [
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Fmascara%20capilar%20de%20tratamiento%20extra%20acida.jpeg?alt=media&token=04e33800-b615-4973-8ca6-fa13eb74621e',
    ],
    variants: false,
  },
  {
    id: 'IcCtZ3JVfX4uaklDL9gw',
    onSale: true,
    isNew: true,
    onCombo: false,
    isFeatured: false,
    name: 'Crema oxigenada ',
    stock: 6,
    minStock: 2,
    sku: '',
    brand: 'MAV',
    category: 'Decolorantes',
    description:
      'Crema Oxigenada Estabilizada Mav Professional Splendore Color.\n\n- Ideal para coloración y decoloración del cabello.\n- Uso profesional.\n- Presentación de 1lt',
    dimensions: {},
    price: 1000,
    salePrice: 900,
    discount: 20,
    image:
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2FWhatsApp%20Image%202022-03-26%20at%2020.36.16.jpeg?alt=media&token=a432da94-7e82-417a-b9c8-0f5ea423b7df',
    gallery: [
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2FWhatsApp%20Image%202022-03-26%20at%2020.36.16.jpeg?alt=media&token=a432da94-7e82-417a-b9c8-0f5ea423b7df',
    ],
    variants: false,
  },
  {
    id: 'Lucu4BDV6EGr3ndkP1fn',
    onSale: true,
    isNew: true,
    onCombo: false,
    isFeatured: true,
    name: 'Polvo Decolorante sin amoniaco',
    stock: 5,
    minStock: 0,
    sku: '',
    brand: 'Everblonde',
    category: 'Decolorantes',
    description:
      'POLVO DECOLORANTE EVERBLONDE\nDECOLORANTE PREMIUM Blanco sin Amoniaco\n\nDISPONIBLE EN: 500gr.',
    dimensions: {},
    price: 1500,
    salePrice: 1125,
    discount: 15,
    image:
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Fbleaching%20powder%20Blonde(green).jpeg?alt=media&token=2e35aa0d-2ae3-4b16-b401-caa59e7cc3a3',
    gallery: [
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Fbleaching%20powder%20Blonde(green).jpeg?alt=media&token=2e35aa0d-2ae3-4b16-b401-caa59e7cc3a3',
    ],
    variants: false,
  },
  {
    id: 'O6GyTXqO8HhMzcdG0Zq9',
    onSale: false,
    isNew: false,
    onCombo: false,
    isFeatured: false,
    name: 'MASCARA HIDRO - NUTRITIVA EN ESTUCHE CAVIAR ',
    stock: 5,
    minStock: 2,
    sku: '',
    brand: 'Fidelité',
    category: 'Tratamiento capilar',
    description:
      '- Tratamiento capilar anti-age con extracto de caviar, D-Pantenol y proteínas de trigo, seda, soja y arroz.\n\n- Combate y retrasa el envejecimiento capilar.\n\n- Devuelve al cabello la vitalidad perdida otorgando brillo, suavidad e hidratación.\n\n- Contiene filtros UV que protegen al cabello de los rayos ultravioleta.',
    dimensions: {},
    price: 700,
    salePrice: 700,
    discount: 0,
    image:
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2FWhatsApp%20Image%202022-03-26%20at%2020.36.19.jpeg?alt=media&token=9c2d41f5-f7c4-4199-998a-ac86ed518edd',
    gallery: [
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2FWhatsApp%20Image%202022-03-26%20at%2020.36.19.jpeg?alt=media&token=9c2d41f5-f7c4-4199-998a-ac86ed518edd',
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2FWhatsApp%20Image%202022-03-09%20at%2020.56.25.jpeg?alt=media&token=9b0b4347-df4d-4733-9599-0edd742b1748',
    ],
    variants: false,
  },
  {
    id: 'UwvTCD0MkGREO3IJ3jg0',
    onSale: false,
    isNew: false,
    onCombo: false,
    isFeatured: false,
    name: 'Tintura Splendore',
    stock: 10,
    minStock: 2,
    sku: '',
    brand: 'MAV',
    category: 'Tinturas',
    description: 'Pomo de tintura permanente de 60grss.',
    dimensions: {},
    price: 300,
    salePrice: 300,
    discount: 0,
    image:
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Ftintura.jpeg?alt=media&token=85806775-eef7-4d8d-bb8f-1c3461cea9c0',
    gallery: [
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Ftintura.jpeg?alt=media&token=85806775-eef7-4d8d-bb8f-1c3461cea9c0',
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Ftintura.jpg?alt=media&token=c7d12a44-094d-4186-b467-b2f25a48b26a',
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Ftintura2.jpg?alt=media&token=d45990a6-cae9-488e-941f-350461ab6e9a',
    ],
    variants: false,
  },
  {
    id: 'XI4ZhOVA0EE5teshWcQq',
    onSale: false,
    isNew: true,
    onCombo: false,
    isFeatured: false,
    name: 'Polvo Decolorante con Keratina',
    stock: 6,
    minStock: 2,
    sku: '',
    brand: 'Issue',
    category: 'Decolorantes',
    description:
      'Polvo Decolorante Issue Aclaro Más Allá del Amarillo White & White 700g\n\nIdeal para una máxima aclaración. Con Keratina\n\nEl polvo decolorante tradicional líder del mercado. Alto rendimiento e ideal para trabajos con gorro y para una máxima decoloración, decolora\nen forma pareja y uniforme.\nNIVEL DE ACLARANTE:\nAclara hasta 7 tonos.\n\nEl producto viene con el modo de uso para cada tipo de aplicación.',
    dimensions: {},
    price: 1500,
    salePrice: 1500,
    discount: 0,
    image:
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Faclarador%20issue%20white%26white.jpeg?alt=media&token=8d96f5f4-0c8d-4d3e-bad1-705e341b467a',
    gallery: [
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Faclarador%20issue%20white%26white.jpeg?alt=media&token=8d96f5f4-0c8d-4d3e-bad1-705e341b467a',
    ],
    variants: false,
  },
  {
    id: 'Xm9SrJ1axXGAfsDqkks9',
    onSale: true,
    isNew: false,
    onCombo: true,
    isFeatured: false,
    name: 'Revelador en crema',
    stock: 12,
    minStock: 2,
    sku: '',
    brand: 'Iyosei Professional ',
    category: 'Decolorantes',
    description:
      'Modo de Empleo: Mezcle el revelador en crema IYOSEI PROFESSIONAL con la coloración capilar o con el polvo decolorante, en las proporciones recomendadas por estos productoss',
    dimensions: {},
    price: 600,
    salePrice: 560,
    discount: 10,
    image:
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Frevelador%20en%20crema2.jpeg?alt=media&token=c409c44a-d6f4-4bc9-ae86-86df66a54e4e',
    gallery: [
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Frevelador%20en%20crema2.jpeg?alt=media&token=c409c44a-d6f4-4bc9-ae86-86df66a54e4e',
    ],
    variants: false,
  },
  {
    id: 'eokrCfOghhyba5D6XoKT',
    onSale: true,
    isNew: false,
    onCombo: false,
    isFeatured: false,
    name: 'Tintura Color Master 60gr X 24unidades + 2 Reveladores 990ml',
    stock: 24,
    minStock: 5,
    sku: 'T00123123',
    brand: 'Color Master',
    category: 'Tinturas',
    description:
      'TINTURA EN CREMA 60g. ALTO PODER CUBRITIVO Y DURABILIDAD DEL COLOR - Disponible: 60 g Fórmula 4 by 4: color tratante - color duradero - color intenso - color brillante. Innovadora coloración en crema, cuida el cabello mientras lo tiñe. 100% efectiva sobre cabellos blanco - Vierta el contenido del pomo de COLORACIÓN COLORMASTER en un bol no metálico. Agregue 90 ml. de REVELADOR EN CREMA COLORMASTER (20 o 30 vol., según el tono deseado). Mezcle con pincel hasta obtener una crema homogénea.  - La mezcla actúa sólo durante 40 minutos: aplicar inmediatamente una vez preparada.  - Cabellos vírgenes: aplicar en medios y puntas y dejar actuar 20 min. Luego, aplicar en las raíces y dejar actuar 40 min. más. Enjuagar.  - Cabellos teñidos o retoques de raíz: aplicar en las raíces y dejar actuar 20 min. Luego extender a largos y puntas dándoles el tiempo de exposición necesario para equilibrar el color. Enjuagar bien.  - Aclarantes: aclaran hasta 3 tonos. Se mezclan con REVELADOR EN CREMA COLORMASTER de 30 vol., proporción 1+1,5. Sólo deben aplicarse en los cabellos sin coloración a partir de un castaño claro.',
    dimensions: {},
    price: 538,
    salePrice: 510.3,
    discount: 20,
    image:
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2F1000032-0.png?alt=media&token=5158e8d9-cd5a-42e8-8f59-e9aa04b0c302',
    gallery: [
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2F1000032-0.png?alt=media&token=5158e8d9-cd5a-42e8-8f59-e9aa04b0c302',
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2F1000033-0.png?alt=media&token=f861f179-6e8b-4176-ae2a-a342bce01b48',
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2F1000006-0.png?alt=media&token=ff1438f3-f803-488d-b408-48ccba6998df',
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2F1000034-0.png?alt=media&token=76151270-aa62-4183-9084-8564e7a8bc74',
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2F1000035-0.png?alt=media&token=f140e281-ff6f-4ccb-b2e0-275fc1bac199',
    ],
    variants: false,
  },
  {
    id: 'hpgvKY3To4azYBwQ5sbJ',
    onSale: false,
    isNew: false,
    onCombo: false,
    isFeatured: false,
    name: 'Tintura Luxury Colors',
    stock: 25,
    minStock: 2,
    sku: '',
    brand: 'Iyosei Professional ',
    category: 'Tinturas',
    description:
      'TINTURA PERMANENTE PARA EL CABELLO IYOSEI PROFESSIONAL\nLUXURY COLORS Unidad de 60g\n\nTINTURA LUXURY COLORS:\nLa más avanzada coloración permanente en crema con tecnología de Micro-Pigmentación. Su fórmula penetra profundamente en la estructura interna del cabello asegurando una cobertura perfecta de las canas. Sus Activos de ARGININA + HIDROLIZADO DE KERATINA [HQ] reestructuran y acondicionan la fibra capilar, disminuyendo la porosidad del cabello logrando un resultado de larga duración.\nSu sistema de colorantes de última generación provee una estructura tridimensional que aumenta la resistencia del color a través de los lavados y el tiempo. Sus componentes acondicionadores alisan la superficie de la fibra capilar disminuyendo la porosidad del cabello tratado y otorgando más brillo y plenitud del color. Los agentes humectantes no iónicos recubren la cutícula asegurando mejor calidad del cabello a través de sucesivas coloraciones',
    dimensions: {},
    price: 300,
    salePrice: 300,
    discount: 0,
    image:
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Ftintura2.jpeg?alt=media&token=e2273e2c-5f9d-4e77-85b7-0827b7f6b10a',
    gallery: [
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Ftintura2.jpeg?alt=media&token=e2273e2c-5f9d-4e77-85b7-0827b7f6b10a',
    ],
    variants: false,
  },
  {
    id: 'kw7XkgZ8wVtr7Ax3VuKv',
    onSale: false,
    isNew: true,
    onCombo: false,
    isFeatured: true,
    name: 'Revelador en crema',
    stock: 6,
    minStock: 2,
    sku: '',
    brand: 'Fidelité',
    category: 'Decolorantes',
    description:
      '// Revelador En Crema X 900ml Caviar Vol 30 //\n- Desarrollado para mezclar únicamente con COLORACIÓN EN CREMA CAVIAR\n- Permite una aplicación localizada y controlable.\n- Viscosidad óptima. Evita el resecamiento. Con una exquisita fragancia.',
    dimensions: {},
    price: 700,
    salePrice: 700,
    discount: 0,
    image:
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Frevelador%20en%20crema.jpeg?alt=media&token=11fbe6dc-37a7-4b1e-b554-c0d54bd024ff',
    gallery: [
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Frevelador%20en%20crema.jpeg?alt=media&token=11fbe6dc-37a7-4b1e-b554-c0d54bd024ff',
    ],
    variants: false,
  },
  {
    id: 'paypO7GIFfnijy4jys1F',
    onSale: true,
    isNew: false,
    onCombo: false,
    isFeatured: true,
    name: 'MYTHICAL MASCARA CAPILAR DE ARGAN',
    stock: 22,
    minStock: 2,
    sku: '',
    brand: 'Fidelité',
    category: 'Tratamiento capilar',
    description:
      '- Es para todo tipo de cabellos. Está hecha a base de aceite virgen de Argán.\n\n- Es un tratamiento anti-age que combate y retarda el envejecimiento capilar.\n\n- Otorga hidratación profunda y nutrición intensa.\n\n- Devuelve la vitalidad perdida al cabello proporcionando una textura ligera y un increíble brillo instantáneo.\n\n- Posee filtros UV y UVB que protegen al cabello de los rayos ultravioleta.\n\n- Antifrizz.',
    dimensions: {},
    price: 700,
    salePrice: 665,
    discount: 5,
    image:
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2FWhatsApp%20Image%202022-03-26%20at%2020.36.19.jpeg?alt=media&token=f018284a-6906-4592-84f2-2693906af41f',
    gallery: [
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2FWhatsApp%20Image%202022-03-26%20at%2020.36.19.jpeg?alt=media&token=f018284a-6906-4592-84f2-2693906af41f',
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2FWhatsApp%20Image%202022-03-26%20at%2020.36.13%20(2).jpeg?alt=media&token=e92d7f05-f19f-43e4-9754-8d9f6714c5cf',
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2FWhatsApp%20Image%202022-03-26%20at%2020.36.13.jpeg?alt=media&token=5a9e978b-c323-42a1-a880-b7af86cdea7a',
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2FWhatsApp%20Image%202022-03-26%20at%2020.36.13.jpeg?alt=media&token=77721c83-0930-490f-ba2b-695b7ed0454a',
    ],
    variants: false,
  },
  {
    id: 'qHw5R5xXMMNQg195k5Ye',
    onSale: false,
    isNew: true,
    onCombo: false,
    isFeatured: false,
    name: 'Tintura Colormaster',
    stock: 20,
    minStock: 2,
    sku: '',
    brand: 'Fidelité',
    category: 'Tinturas',
    description:
      '- Fórmula 4 by 4:\n\n- Color tratante\n\n- Color duradero\n\n- Color intenso\n\n- Color brillante.\n\n- Formulación 1 x 1 1/2\n\n-Innovadora coloración en crema, cuida el cabello mientras lo tiñe.\n\n-100% efectiva sobre cabellos blancos.',
    dimensions: {},
    price: 265,
    salePrice: 265,
    discount: 0,
    image:
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Fcolormaster%20tintura.jpeg?alt=media&token=280ab794-e6cd-4b44-a49c-4038856cafcd',
    gallery: [
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Fcolormaster%20tintura.jpeg?alt=media&token=280ab794-e6cd-4b44-a49c-4038856cafcd',
    ],
    variants: false,
  },
  {
    id: 'vmMctTIbYSI4JnFm9RpY',
    onSale: true,
    isNew: true,
    onCombo: false,
    isFeatured: false,
    name: 'Máscara Reestructurante con Aceite de Lino',
    stock: 7,
    minStock: 2,
    sku: '',
    brand: 'Iyosei Professional ',
    category: 'Tratamiento capilar',
    description:
      'El Tratamiento de re-estructuración es un proceso de reparación de efecto intensivo para todo tipo de cabellos.\nSu eficaz fórmula con Aceite de semillas de Lino + Pro Keratina ayuda a reestructurar, nutrir e hidratar, de manera profunda la fibra capilar, desde su interior.\nProduce un efecto inmediato en el aspecto exterior del cabello, cauterizando la cutícula para dar como resultado flexibilidad y luminosidad a los cabellos, devolviéndole además, salud y vitalidad.\nSulfate Free\nPH acido\nDesarrollado para cabellos dañados post coloración',
    dimensions: {},
    price: 2400,
    salePrice: 2160,
    discount: 10,
    image:
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Fmascara.jpeg?alt=media&token=2deb3f0b-41a8-4824-968e-52f961177193',
    gallery: [
      'https://firebasestorage.googleapis.com/v0/b/fontaine-dev.appspot.com/o/products%2Fmascara.jpeg?alt=media&token=2deb3f0b-41a8-4824-968e-52f961177193',
    ],
    variants: false,
  },
];

export const categoriesSeed: ICategoryBackend[] = [
  {
    id: '4oCgr0miSyFMgvT6X963',
    slug: 'anti-edad',
    name: 'Anti-edad',
  },
  {
    id: 'Swf4CVhF6VquZRE7IHdq',
    slug: 'tinturas',
    name: 'Tinturas',
  },
  {
    id: 'W6QsQJSjHV1x6twGF2AO',
    slug: 'anticaspa',
    name: 'Anticaspa',
  },
  {
    id: 'e9GH3MPY2iPfDF6dUMP0',
    slug: 'decolorantes',
    name: 'Decolorantes',
  },
  {
    id: 'nuPIZPByJGa60C3tgNaB',
    slug: 'tratamientos',
    name: 'Tratamientos',
  },
  {
    id: 'ogPq6TLJgJUrcRUaEjtP',
    slug: 'tratamiento-capilar',
    name: 'Tratamiento capilar',
  },
  {
    id: 'qoIKhUPVtt5qN3sHj3pe',
    slug: 'anticaspa-2',
    name: 'anticaspa',
  },
  {
    id: 'sEmPQQxQhkQDohIf06Wb',
    slug: 'crema-de-enjuague',
    name: 'Crema de enjuague',
  },
  {
    id: 't1OFaTV1baqWFTJAin67',
    slug: 'shampoos',
    name: 'Shampoos',
  },
];
export default { productSeed, categoriesSeed };
